# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fgr.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class FgrWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(476, 223)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 60, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 30, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.textEdita1 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdita1.setGeometry(QtCore.QRect(40, 135, 71, 21))
        self.textEdita1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdita1.setObjectName("textEdita1")
        self.textEditb2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditb2.setGeometry(QtCore.QRect(150, 80, 71, 21))
        self.textEditb2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditb2.setObjectName("textEditb2")
        self.textEditk1 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditk1.setGeometry(QtCore.QRect(40, 55, 71, 21))
        self.textEditk1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditk1.setObjectName("textEditk1")
        self.textEditb1 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditb1.setGeometry(QtCore.QRect(150, 55, 71, 21))
        self.textEditb1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditb1.setObjectName("textEditb1")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 160, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 80, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textEditk2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditk2.setGeometry(QtCore.QRect(40, 80, 71, 21))
        self.textEditk2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditk2.setObjectName("textEditk2")
        self.textEdita2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdita2.setGeometry(QtCore.QRect(40, 160, 71, 21))
        self.textEdita2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdita2.setObjectName("textEdita2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 140, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 60, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.make = QtWidgets.QPushButton(self.centralwidget)
        self.make.setGeometry(QtCore.QRect(370, 150, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.make.setFont(font)
        self.make.setObjectName("make")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 110, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(160, 10, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.parStxt = QtWidgets.QLabel(self.centralwidget)
        self.parStxt.setGeometry(QtCore.QRect(240, 50, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.parStxt.setFont(font)
        self.parStxt.setObjectName("parStxt")
        self.textEditEpar = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditEpar.setGeometry(QtCore.QRect(290, 76, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditEpar.setFont(font)
        self.textEditEpar.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditEpar.setUndoRedoEnabled(True)
        self.textEditEpar.setAcceptRichText(True)
        self.textEditEpar.setObjectName("textEditEpar")
        self.textEditSpar = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditSpar.setGeometry(QtCore.QRect(290, 50, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditSpar.setFont(font)
        self.textEditSpar.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditSpar.setDocumentTitle("")
        self.textEditSpar.setUndoRedoEnabled(True)
        self.textEditSpar.setOverwriteMode(False)
        self.textEditSpar.setAcceptRichText(True)
        self.textEditSpar.setObjectName("textEditSpar")
        self.parEtxt = QtWidgets.QLabel(self.centralwidget)
        self.parEtxt.setGeometry(QtCore.QRect(240, 70, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.parEtxt.setFont(font)
        self.parEtxt.setObjectName("parEtxt")
        self.parEEtxt = QtWidgets.QLabel(self.centralwidget)
        self.parEEtxt.setGeometry(QtCore.QRect(250, 102, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.parEEtxt.setFont(font)
        self.parEEtxt.setObjectName("parEEtxt")
        self.textEditEEpar = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditEEpar.setGeometry(QtCore.QRect(290, 102, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditEEpar.setFont(font)
        self.textEditEEpar.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditEEpar.setUndoRedoEnabled(True)
        self.textEditEEpar.setAcceptRichText(True)
        self.textEditEEpar.setObjectName("textEditEEpar")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(400, 30, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.parStxt_2 = QtWidgets.QLabel(self.centralwidget)
        self.parStxt_2.setGeometry(QtCore.QRect(370, 50, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.parStxt_2.setFont(font)
        self.parStxt_2.setObjectName("parStxt_2")
        self.parStxt_3 = QtWidgets.QLabel(self.centralwidget)
        self.parStxt_3.setGeometry(QtCore.QRect(370, 73, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.parStxt_3.setFont(font)
        self.parStxt_3.setObjectName("parStxt_3")
        self.parStxt_4 = QtWidgets.QLabel(self.centralwidget)
        self.parStxt_4.setGeometry(QtCore.QRect(370, 96, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.parStxt_4.setFont(font)
        self.parStxt_4.setObjectName("parStxt_4")
        self.parStxt_5 = QtWidgets.QLabel(self.centralwidget)
        self.parStxt_5.setGeometry(QtCore.QRect(370, 119, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.parStxt_5.setFont(font)
        self.parStxt_5.setObjectName("parStxt_5")
        self.textEditSpar_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditSpar_2.setGeometry(QtCore.QRect(400, 50, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditSpar_2.setFont(font)
        self.textEditSpar_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditSpar_2.setDocumentTitle("")
        self.textEditSpar_2.setUndoRedoEnabled(True)
        self.textEditSpar_2.setOverwriteMode(False)
        self.textEditSpar_2.setAcceptRichText(True)
        self.textEditSpar_2.setObjectName("textEditSpar_2")
        self.textEditSpar_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditSpar_3.setGeometry(QtCore.QRect(400, 73, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditSpar_3.setFont(font)
        self.textEditSpar_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditSpar_3.setDocumentTitle("")
        self.textEditSpar_3.setUndoRedoEnabled(True)
        self.textEditSpar_3.setOverwriteMode(False)
        self.textEditSpar_3.setAcceptRichText(True)
        self.textEditSpar_3.setObjectName("textEditSpar_3")
        self.textEditSpar_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditSpar_4.setGeometry(QtCore.QRect(400, 96, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditSpar_4.setFont(font)
        self.textEditSpar_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditSpar_4.setDocumentTitle("")
        self.textEditSpar_4.setUndoRedoEnabled(True)
        self.textEditSpar_4.setOverwriteMode(False)
        self.textEditSpar_4.setAcceptRichText(True)
        self.textEditSpar_4.setObjectName("textEditSpar_4")
        self.textEditSpar_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditSpar_5.setGeometry(QtCore.QRect(400, 119, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditSpar_5.setFont(font)
        self.textEditSpar_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditSpar_5.setDocumentTitle("")
        self.textEditSpar_5.setUndoRedoEnabled(True)
        self.textEditSpar_5.setOverwriteMode(False)
        self.textEditSpar_5.setAcceptRichText(True)
        self.textEditSpar_5.setObjectName("textEditSpar_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 476, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "k1="))
        self.label_7.setText(_translate("MainWindow", "Пр-ы линейных ф."))
        self.label_2.setText(_translate("MainWindow", "k2="))
        self.textEdita1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">5</span></p></body></html>"))
        self.textEdita1.setPlaceholderText(_translate("MainWindow", "5"))
        self.textEditb2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">-0.22</span></p></body></html>"))
        self.textEditb2.setPlaceholderText(_translate("MainWindow", "-0.22"))
        self.textEditk1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">1.15</span></p></body></html>"))
        self.textEditk1.setPlaceholderText(_translate("MainWindow", "1.15"))
        self.textEditb1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">0</span></p></body></html>"))
        self.textEditb1.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "a2="))
        self.label_4.setText(_translate("MainWindow", "b2="))
        self.textEditk2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">-2</span></p></body></html>"))
        self.textEditk2.setPlaceholderText(_translate("MainWindow", "-2"))
        self.textEdita2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">-5</span></p></body></html>"))
        self.textEdita2.setPlaceholderText(_translate("MainWindow", "-5"))
        self.label_6.setText(_translate("MainWindow", "a1="))
        self.label_3.setText(_translate("MainWindow", "b1="))
        self.make.setText(_translate("MainWindow", "Построить"))
        self.label_8.setText(_translate("MainWindow", "Пр-ы экспоненциальных ф."))
        self.label_9.setText(_translate("MainWindow", "4 графика функций"))
        self.parStxt.setText(_translate("MainWindow", "Старт="))
        self.textEditEpar.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0.5</p></body></html>"))
        self.textEditEpar.setPlaceholderText(_translate("MainWindow", "0.5"))
        self.textEditSpar.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-0.5</p></body></html>"))
        self.textEditSpar.setPlaceholderText(_translate("MainWindow", "-0.5"))
        self.parEtxt.setText(_translate("MainWindow", "Конец="))
        self.parEEtxt.setText(_translate("MainWindow", "Шаг="))
        self.textEditEEpar.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0.001</p></body></html>"))
        self.textEditEEpar.setPlaceholderText(_translate("MainWindow", "0.001"))
        self.label_10.setText(_translate("MainWindow", "Подписи"))
        self.parStxt_2.setText(_translate("MainWindow", "y1="))
        self.parStxt_3.setText(_translate("MainWindow", "y2="))
        self.parStxt_4.setText(_translate("MainWindow", "y3="))
        self.parStxt_5.setText(_translate("MainWindow", "y4="))
        self.textEditSpar_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">kx</p></body></html>"))
        self.textEditSpar_2.setPlaceholderText(_translate("MainWindow", "kx"))
        self.textEditSpar_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">kx+b</p></body></html>"))
        self.textEditSpar_3.setPlaceholderText(_translate("MainWindow", "kx+b"))
        self.textEditSpar_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">e^a</p></body></html>"))
        self.textEditSpar_4.setPlaceholderText(_translate("MainWindow", "e^a"))
        self.textEditSpar_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">e^(-a)</p></body></html>"))
        self.textEditSpar_5.setPlaceholderText(_translate("MainWindow", "e^(-a)"))

