# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'partwin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PartWin(object):
    def setupUi(self, PartWin):
        PartWin.setObjectName("PartWin")
        PartWin.resize(347, 197)
        PartWin.setMaximumSize(QtCore.QSize(347, 197))
        self.linbutt = QtWidgets.QPushButton(PartWin)
        self.linbutt.setGeometry(QtCore.QRect(240, 120, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.linbutt.setFont(font)
        self.linbutt.setObjectName("linbutt")
        self.parStxt = QtWidgets.QLabel(PartWin)
        self.parStxt.setGeometry(QtCore.QRect(220, 30, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.parStxt.setFont(font)
        self.parStxt.setObjectName("parStxt")
        self.parEtxt = QtWidgets.QLabel(PartWin)
        self.parEtxt.setGeometry(QtCore.QRect(220, 54, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.parEtxt.setFont(font)
        self.parEtxt.setObjectName("parEtxt")
        self.textEditSpar = QtWidgets.QTextEdit(PartWin)
        self.textEditSpar.setGeometry(QtCore.QRect(270, 30, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditSpar.setFont(font)
        self.textEditSpar.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditSpar.setDocumentTitle("")
        self.textEditSpar.setUndoRedoEnabled(True)
        self.textEditSpar.setOverwriteMode(False)
        self.textEditSpar.setAcceptRichText(True)
        self.textEditSpar.setObjectName("textEditSpar")
        self.textEditEpar = QtWidgets.QTextEdit(PartWin)
        self.textEditEpar.setGeometry(QtCore.QRect(270, 60, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditEpar.setFont(font)
        self.textEditEpar.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditEpar.setUndoRedoEnabled(True)
        self.textEditEpar.setAcceptRichText(True)
        self.textEditEpar.setObjectName("textEditEpar")
        self.textEditEEpar = QtWidgets.QTextEdit(PartWin)
        self.textEditEEpar.setGeometry(QtCore.QRect(270, 90, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditEEpar.setFont(font)
        self.textEditEEpar.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditEEpar.setUndoRedoEnabled(True)
        self.textEditEEpar.setAcceptRichText(True)
        self.textEditEEpar.setObjectName("textEditEEpar")
        self.parEEtxt = QtWidgets.QLabel(PartWin)
        self.parEEtxt.setGeometry(QtCore.QRect(230, 90, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.parEEtxt.setFont(font)
        self.parEEtxt.setObjectName("parEEtxt")
        self.label = QtWidgets.QLabel(PartWin)
        self.label.setGeometry(QtCore.QRect(100, 0, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEditEpar_2 = QtWidgets.QTextEdit(PartWin)
        self.textEditEpar_2.setGeometry(QtCore.QRect(40, 56, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditEpar_2.setFont(font)
        self.textEditEpar_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditEpar_2.setUndoRedoEnabled(True)
        self.textEditEpar_2.setAcceptRichText(True)
        self.textEditEpar_2.setObjectName("textEditEpar_2")
        self.parktxt = QtWidgets.QLabel(PartWin)
        self.parktxt.setGeometry(QtCore.QRect(10, 30, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.parktxt.setFont(font)
        self.parktxt.setObjectName("parktxt")
        self.textEditKpar = QtWidgets.QTextEdit(PartWin)
        self.textEditKpar.setGeometry(QtCore.QRect(40, 31, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditKpar.setFont(font)
        self.textEditKpar.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditKpar.setUndoRedoEnabled(True)
        self.textEditKpar.setAcceptRichText(True)
        self.textEditKpar.setObjectName("textEditKpar")
        self.paEtxt_2 = QtWidgets.QLabel(PartWin)
        self.paEtxt_2.setGeometry(QtCore.QRect(10, 50, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.paEtxt_2.setFont(font)
        self.paEtxt_2.setObjectName("paEtxt_2")
        self.textEditEpar_3 = QtWidgets.QTextEdit(PartWin)
        self.textEditEpar_3.setGeometry(QtCore.QRect(40, 105, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditEpar_3.setFont(font)
        self.textEditEpar_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditEpar_3.setUndoRedoEnabled(True)
        self.textEditEpar_3.setAcceptRichText(True)
        self.textEditEpar_3.setObjectName("textEditEpar_3")
        self.paEtxt_3 = QtWidgets.QLabel(PartWin)
        self.paEtxt_3.setGeometry(QtCore.QRect(10, 99, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.paEtxt_3.setFont(font)
        self.paEtxt_3.setObjectName("paEtxt_3")
        self.parktxt_2 = QtWidgets.QLabel(PartWin)
        self.parktxt_2.setGeometry(QtCore.QRect(10, 79, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.parktxt_2.setFont(font)
        self.parktxt_2.setObjectName("parktxt_2")
        self.textEditKpar_2 = QtWidgets.QTextEdit(PartWin)
        self.textEditKpar_2.setGeometry(QtCore.QRect(40, 80, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditKpar_2.setFont(font)
        self.textEditKpar_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditKpar_2.setUndoRedoEnabled(True)
        self.textEditKpar_2.setAcceptRichText(True)
        self.textEditKpar_2.setObjectName("textEditKpar_2")
        self.textEditKpar_3 = QtWidgets.QTextEdit(PartWin)
        self.textEditKpar_3.setGeometry(QtCore.QRect(40, 131, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditKpar_3.setFont(font)
        self.textEditKpar_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditKpar_3.setUndoRedoEnabled(True)
        self.textEditKpar_3.setAcceptRichText(True)
        self.textEditKpar_3.setObjectName("textEditKpar_3")
        self.parktxt_3 = QtWidgets.QLabel(PartWin)
        self.parktxt_3.setGeometry(QtCore.QRect(10, 130, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.parktxt_3.setFont(font)
        self.parktxt_3.setObjectName("parktxt_3")
        self.textEditEpar_4 = QtWidgets.QTextEdit(PartWin)
        self.textEditEpar_4.setGeometry(QtCore.QRect(40, 156, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditEpar_4.setFont(font)
        self.textEditEpar_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditEpar_4.setUndoRedoEnabled(True)
        self.textEditEpar_4.setAcceptRichText(True)
        self.textEditEpar_4.setObjectName("textEditEpar_4")
        self.paEtxt_4 = QtWidgets.QLabel(PartWin)
        self.paEtxt_4.setGeometry(QtCore.QRect(10, 150, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.paEtxt_4.setFont(font)
        self.paEtxt_4.setObjectName("paEtxt_4")
        self.textEditKpar_4 = QtWidgets.QTextEdit(PartWin)
        self.textEditKpar_4.setGeometry(QtCore.QRect(150, 79, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditKpar_4.setFont(font)
        self.textEditKpar_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditKpar_4.setUndoRedoEnabled(True)
        self.textEditKpar_4.setAcceptRichText(True)
        self.textEditKpar_4.setObjectName("textEditKpar_4")
        self.parktxt_4 = QtWidgets.QLabel(PartWin)
        self.parktxt_4.setGeometry(QtCore.QRect(120, 78, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.parktxt_4.setFont(font)
        self.parktxt_4.setObjectName("parktxt_4")
        self.textEditEpar_5 = QtWidgets.QTextEdit(PartWin)
        self.textEditEpar_5.setGeometry(QtCore.QRect(150, 55, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditEpar_5.setFont(font)
        self.textEditEpar_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditEpar_5.setUndoRedoEnabled(True)
        self.textEditEpar_5.setAcceptRichText(True)
        self.textEditEpar_5.setObjectName("textEditEpar_5")
        self.paEtxt_5 = QtWidgets.QLabel(PartWin)
        self.paEtxt_5.setGeometry(QtCore.QRect(120, 49, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.paEtxt_5.setFont(font)
        self.paEtxt_5.setObjectName("paEtxt_5")
        self.textEditEpar_6 = QtWidgets.QTextEdit(PartWin)
        self.textEditEpar_6.setGeometry(QtCore.QRect(150, 104, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditEpar_6.setFont(font)
        self.textEditEpar_6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditEpar_6.setUndoRedoEnabled(True)
        self.textEditEpar_6.setAcceptRichText(True)
        self.textEditEpar_6.setObjectName("textEditEpar_6")
        self.paEtxt_6 = QtWidgets.QLabel(PartWin)
        self.paEtxt_6.setGeometry(QtCore.QRect(120, 98, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.paEtxt_6.setFont(font)
        self.paEtxt_6.setObjectName("paEtxt_6")
        self.parktxt_5 = QtWidgets.QLabel(PartWin)
        self.parktxt_5.setGeometry(QtCore.QRect(120, 29, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.parktxt_5.setFont(font)
        self.parktxt_5.setObjectName("parktxt_5")
        self.textEditKpar_5 = QtWidgets.QTextEdit(PartWin)
        self.textEditKpar_5.setGeometry(QtCore.QRect(150, 30, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditKpar_5.setFont(font)
        self.textEditKpar_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditKpar_5.setUndoRedoEnabled(True)
        self.textEditKpar_5.setAcceptRichText(True)
        self.textEditKpar_5.setObjectName("textEditKpar_5")

        self.retranslateUi(PartWin)
        QtCore.QMetaObject.connectSlotsByName(PartWin)

    def retranslateUi(self, PartWin):
        _translate = QtCore.QCoreApplication.translate
        PartWin.setWindowTitle(_translate("PartWin", "Параметры"))
        self.linbutt.setText(_translate("PartWin", "График"))
        self.parStxt.setText(_translate("PartWin", "Старт="))
        self.parEtxt.setText(_translate("PartWin", "Конец="))
        self.textEditSpar.setHtml(_translate("PartWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.textEditSpar.setPlaceholderText(_translate("PartWin", "0"))
        self.textEditEpar.setHtml(_translate("PartWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1000</p></body></html>"))
        self.textEditEpar.setPlaceholderText(_translate("PartWin", "1000"))
        self.textEditEEpar.setHtml(_translate("PartWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1</p></body></html>"))
        self.textEditEEpar.setPlaceholderText(_translate("PartWin", "1"))
        self.parEEtxt.setText(_translate("PartWin", "Шаг="))
        self.label.setText(_translate("PartWin", "Кусочная функция"))
        self.textEditEpar_2.setHtml(_translate("PartWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1</p></body></html>"))
        self.textEditEpar_2.setPlaceholderText(_translate("PartWin", "1"))
        self.parktxt.setText(_translate("PartWin", "k1="))
        self.textEditKpar.setHtml(_translate("PartWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-1</p></body></html>"))
        self.textEditKpar.setPlaceholderText(_translate("PartWin", "-1"))
        self.paEtxt_2.setText(_translate("PartWin", "k2="))
        self.textEditEpar_3.setHtml(_translate("PartWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-245</p></body></html>"))
        self.textEditEpar_3.setPlaceholderText(_translate("PartWin", "-245"))
        self.paEtxt_3.setText(_translate("PartWin", "b2="))
        self.parktxt_2.setText(_translate("PartWin", "b1="))
        self.textEditKpar_2.setHtml(_translate("PartWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">755</p></body></html>"))
        self.textEditKpar_2.setPlaceholderText(_translate("PartWin", "755"))
        self.textEditKpar_3.setHtml(_translate("PartWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0.025</p></body></html>"))
        self.textEditKpar_3.setPlaceholderText(_translate("PartWin", "0.025"))
        self.parktxt_3.setText(_translate("PartWin", "a1="))
        self.textEditEpar_4.setHtml(_translate("PartWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-0.025</p></body></html>"))
        self.textEditEpar_4.setPlaceholderText(_translate("PartWin", "-0.025"))
        self.paEtxt_4.setText(_translate("PartWin", "a2="))
        self.textEditKpar_4.setHtml(_translate("PartWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1</p></body></html>"))
        self.textEditKpar_4.setPlaceholderText(_translate("PartWin", "1"))
        self.parktxt_4.setText(_translate("PartWin", "c3="))
        self.textEditEpar_5.setHtml(_translate("PartWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1</p></body></html>"))
        self.textEditEpar_5.setPlaceholderText(_translate("PartWin", "1"))
        self.paEtxt_5.setText(_translate("PartWin", "c2="))
        self.textEditEpar_6.setHtml(_translate("PartWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">70000000000</p></body></html>"))
        self.textEditEpar_6.setPlaceholderText(_translate("PartWin", "70000000000"))
        self.paEtxt_6.setText(_translate("PartWin", "c4="))
        self.parktxt_5.setText(_translate("PartWin", "c1="))
        self.textEditKpar_5.setHtml(_translate("PartWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1</p></body></html>"))
        self.textEditKpar_5.setPlaceholderText(_translate("PartWin", "1"))

