# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spik.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Ui_spik(object):
    def setupUi(self, Ui_spik):
        Ui_spik.setObjectName("Ui_spik")
        Ui_spik.resize(301, 271)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_spik.sizePolicy().hasHeightForWidth())
        Ui_spik.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(Ui_spik)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 122, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.parStxt = QtWidgets.QLabel(self.centralwidget)
        self.parStxt.setGeometry(QtCore.QRect(20, 44, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.parStxt.setFont(font)
        self.parStxt.setObjectName("parStxt")
        self.parEtxt = QtWidgets.QLabel(self.centralwidget)
        self.parEtxt.setGeometry(QtCore.QRect(20, 64, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.parEtxt.setFont(font)
        self.parEtxt.setObjectName("parEtxt")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 10, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.linbutt = QtWidgets.QPushButton(self.centralwidget)
        self.linbutt.setGeometry(QtCore.QRect(140, 210, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.linbutt.setFont(font)
        self.linbutt.setObjectName("linbutt")
        self.textEditSpar = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditSpar.setGeometry(QtCore.QRect(70, 44, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditSpar.setFont(font)
        self.textEditSpar.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditSpar.setDocumentTitle("")
        self.textEditSpar.setUndoRedoEnabled(True)
        self.textEditSpar.setOverwriteMode(False)
        self.textEditSpar.setAcceptRichText(True)
        self.textEditSpar.setObjectName("textEditSpar")
        self.textEditEpar = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditEpar.setGeometry(QtCore.QRect(70, 70, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditEpar.setFont(font)
        self.textEditEpar.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditEpar.setUndoRedoEnabled(True)
        self.textEditEpar.setAcceptRichText(True)
        self.textEditEpar.setObjectName("textEditEpar")
        self.parEEtxt = QtWidgets.QLabel(self.centralwidget)
        self.parEEtxt.setGeometry(QtCore.QRect(30, 96, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.parEEtxt.setFont(font)
        self.parEEtxt.setObjectName("parEEtxt")
        self.textEditEEpar = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditEEpar.setGeometry(QtCore.QRect(70, 96, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditEEpar.setFont(font)
        self.textEditEEpar.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditEEpar.setUndoRedoEnabled(True)
        self.textEditEEpar.setAcceptRichText(True)
        self.textEditEEpar.setObjectName("textEditEEpar")
        self.lim2 = QtWidgets.QTextEdit(self.centralwidget)
        self.lim2.setGeometry(QtCore.QRect(70, 148, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lim2.setFont(font)
        self.lim2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lim2.setUndoRedoEnabled(True)
        self.lim2.setAcceptRichText(True)
        self.lim2.setObjectName("lim2")
        self.lim1 = QtWidgets.QTextEdit(self.centralwidget)
        self.lim1.setGeometry(QtCore.QRect(70, 122, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lim1.setFont(font)
        self.lim1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lim1.setUndoRedoEnabled(True)
        self.lim1.setAcceptRichText(True)
        self.lim1.setObjectName("lim1")
        self.textEditEEpar_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditEEpar_2.setGeometry(QtCore.QRect(210, 44, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEditEEpar_2.setFont(font)
        self.textEditEEpar_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEditEEpar_2.setUndoRedoEnabled(True)
        self.textEditEEpar_2.setAcceptRichText(True)
        self.textEditEEpar_2.setObjectName("textEditEEpar_2")
        self.parEEtxt_2 = QtWidgets.QLabel(self.centralwidget)
        self.parEEtxt_2.setGeometry(QtCore.QRect(140, 44, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.parEEtxt_2.setFont(font)
        self.parEEtxt_2.setObjectName("parEEtxt_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(140, 70, 151, 41))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setGeometry(QtCore.QRect(5, 0, 141, 17))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setGeometry(QtCore.QRect(5, 20, 141, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.lim1_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.lim1_2.setGeometry(QtCore.QRect(220, 122, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lim1_2.setFont(font)
        self.lim1_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lim1_2.setUndoRedoEnabled(True)
        self.lim1_2.setAcceptRichText(True)
        self.lim1_2.setObjectName("lim1_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 122, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(140, 150, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lim1_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.lim1_3.setGeometry(QtCore.QRect(220, 150, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lim1_3.setFont(font)
        self.lim1_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lim1_3.setUndoRedoEnabled(True)
        self.lim1_3.setAcceptRichText(True)
        self.lim1_3.setObjectName("lim1_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(140, 180, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lim1_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.lim1_4.setGeometry(QtCore.QRect(220, 180, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lim1_4.setFont(font)
        self.lim1_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lim1_4.setUndoRedoEnabled(True)
        self.lim1_4.setAcceptRichText(True)
        self.lim1_4.setObjectName("lim1_4")
        Ui_spik.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ui_spik)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 301, 21))
        self.menubar.setObjectName("menubar")
        Ui_spik.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ui_spik)
        self.statusbar.setObjectName("statusbar")
        Ui_spik.setStatusBar(self.statusbar)

        self.retranslateUi(Ui_spik)
        QtCore.QMetaObject.connectSlotsByName(Ui_spik)

    def retranslateUi(self, Ui_spik):
        _translate = QtCore.QCoreApplication.translate
        Ui_spik.setWindowTitle(_translate("Ui_spik", "Параметры"))
        self.label_2.setText(_translate("Ui_spik", "Пределы"))
        self.parStxt.setText(_translate("Ui_spik", "Старт="))
        self.parEtxt.setText(_translate("Ui_spik", "Конец="))
        self.label.setText(_translate("Ui_spik", "Скачки значений"))
        self.linbutt.setText(_translate("Ui_spik", "График"))
        self.textEditSpar.setHtml(_translate("Ui_spik", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.textEditSpar.setPlaceholderText(_translate("Ui_spik", "0"))
        self.textEditEpar.setHtml(_translate("Ui_spik", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1000</p></body></html>"))
        self.textEditEpar.setPlaceholderText(_translate("Ui_spik", "1000"))
        self.parEEtxt.setText(_translate("Ui_spik", "Шаг="))
        self.textEditEEpar.setHtml(_translate("Ui_spik", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1</p></body></html>"))
        self.textEditEEpar.setPlaceholderText(_translate("Ui_spik", "1"))
        self.lim2.setPlaceholderText(_translate("Ui_spik", "None"))
        self.lim1.setPlaceholderText(_translate("Ui_spik", "None"))
        self.textEditEEpar_2.setHtml(_translate("Ui_spik", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1</p></body></html>"))
        self.textEditEEpar_2.setPlaceholderText(_translate("Ui_spik", "1"))
        self.parEEtxt_2.setText(_translate("Ui_spik", "Масштаб="))
        self.radioButton.setText(_translate("Ui_spik", "Встроенный генератор"))
        self.radioButton_2.setText(_translate("Ui_spik", "Свой генератор"))
        self.lim1_2.setHtml(_translate("Ui_spik", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1</p></body></html>"))
        self.lim1_2.setPlaceholderText(_translate("Ui_spik", "1"))
        self.label_3.setText(_translate("Ui_spik", "Кол-во(%)="))
        self.label_4.setText(_translate("Ui_spik", "Амплит-а="))
        self.lim1_3.setHtml(_translate("Ui_spik", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1.2</p></body></html>"))
        self.lim1_3.setPlaceholderText(_translate("Ui_spik", "1.2"))
        self.label_5.setText(_translate("Ui_spik", "Разброс="))
        self.lim1_4.setHtml(_translate("Ui_spik", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0.5</p></body></html>"))
        self.lim1_4.setPlaceholderText(_translate("Ui_spik", "0.5"))

